### PR TITLE
Unified tables

### PR DESCRIPTION
**Pull request by 35359595**
Remove of Out_of_order table and changes to `compute_state()` to:
- Avoid re-calculation of the state on each out_of_order event present in the db when processing new event;
- Avoid move of the event in the DB when it is no longer out of order;

### CODE REVIEW

**Comment by blelump** [comment]
I suppose the database model has been prepared in such way to focus on heavy read ( @chunningham please correct me if i'm mistaken ), so we don't process given identifier events each time when someone else comes and wants to get its KEL. On the other hand, when the out of order events are also part of the events of given identifier, we need to process them every time to filter the out of order events. As an alternative we could send everything to the KEL requestor and move all the processing to its shoulders, but then we exchange events, that have no value basically for the requestor. Even if the out of order events could expire after some time, at scale that might be a problem that is not straightforward to forget.

Last but not least, I guess Charles intention here was to consider even complex writes as cheaper than reads, because in the end reads happen much more frequently than writes. So having pre-computed state for reads allows to return exactly what is needed.

**Comment by 35359595** [comment]
1. Identity holder's KEL  should never have Out of order or Partially signed events;
2. Read from DB happens :

    a. on new message arrival (or full updated KEL maybe?), which in turn forces full state re-calculation from DB and triggers problems this PR intended to solve (re-calk each present out-of-order or partially signed event from dedicated table); 

    b. on re-construction of indentifier's KERL (not KEL) with receipts included: for now (as there is no spec) it's not 100% clear to me what purpose it serves so I've not included duplicity events in it YET. If it's for witness to witness/judge/watcher/juror/ect. sync then those invents inclusion may be required anyways (including duplicitous).

**Comment by 35359595** [comment]
@chunningham can you share your opinion on this please?

**Comment by bumblefudge** [comment]
Discussed a little on call 7/20 - conversation to continue here or on DIF Slack

**Comment by blelump** [comment]
Discussed it on weekly KERIOX call and decided that we merge this PR as is. The outcome of this PR is that all out-of-order-events and partially-signed-events will be stored in the same table as the remaining (processed) events so any `get_kel` operation will return basically everything. Whether this is good or bad approach it depends on the perspective and we assume that in case of ie. mirroring of KEL it is wiser to get it as is, so nothing is lost.

It opens another issues like bloating the KEL's that are being kept ie. by witnesses, but we left them open for future considerations.

**Pull request merged**
